import {LocationModelSuggest} from '../models/LocationModel';

const locationsDataFake: LocationModelSuggest[] = [
  {
    place_id: '1',
    description: 'Quận Hoàn Kiếm, Hà Nội, Việt Nam',
    main_name_place: 'Hoàn Kiếm Lake',
    latitude: 21.028511,
    longitude: 105.854444,
  },
  {
    place_id: '2',
    description: '58 Quốc Tử Giám, Văn Miếu, Đống Đa, Hà Nội, Việt Nam',
    main_name_place: 'Temple of Literature',
    latitude: 21.02774,
    longitude: 105.835085,
  },
  {
    place_id: '3',
    description: '191 Bà Triệu, Hai Bà Trưng, Hà Nội, Việt Nam',
    main_name_place: 'Vincom Center Ba Trieu',
    latitude: 21.027378,
    longitude: 105.858426,
  },
  {
    place_id: '4',
    description: 'Tây Hồ, Hà Nội, Việt Nam',
    main_name_place: 'West Lake',
    latitude: 21.070207,
    longitude: 105.854444,
  },
  {
    place_id: '5',
    description: '213 Đường Láng, Đống Đa, Hà Nội, Việt Nam',
    main_name_place: 'Thu Le Park',
    latitude: 21.036604,
    longitude: 105.803825,
  },
  {
    place_id: '6',
    description: 'Quận Hoàn Kiếm, Hà Nội, Việt Nam',
    main_name_place: 'Old Quarter',
    latitude: 21.033888,
    longitude: 105.850558,
  },
  {
    place_id: '7',
    description: '27 Cổ Linh, Long Biên, Hà Nội, Việt Nam',
    main_name_place: 'Aeon Mall Long Bien',
    latitude: 21.065729,
    longitude: 105.883975,
  },
  {
    place_id: '8',
    description: '1 Hoả Lò, Trần Hưng Đạo, Hoàn Kiếm, Hà Nội, Việt Nam',
    main_name_place: 'Hoa Lo Prison',
    latitude: 21.02211,
    longitude: 105.855081,
  },
  {
    place_id: '9',
    description: 'Ba Đình, Hà Nội, Việt Nam',
    main_name_place: 'Ba Dinh Square',
    latitude: 21.027562,
    longitude: 105.832519,
  },
  {
    place_id: '10',
    description: '66 Nguyễn Thái Học, Quốc Tử Giám, Đống Đa, Hà Nội, Việt Nam',
    main_name_place: 'Vietnam Fine Arts Museum',
    latitude: 21.027858,
    longitude: 105.833199,
  },
  {
    place_id: '11',
    description: 'Ciputra, Tây Hồ, Hà Nội, Việt Nam',
    main_name_place: 'Ciputra Hanoi',
    latitude: 21.04876,
    longitude: 105.826091,
  },
  // {
  //   place_id: '12',
  //   description: 'Long Biên, Hà Nội, Việt Nam',
  //   main_name_place: 'Long Bien Bridge',
  //   latitude: 21.0542,
  //   longitude: 105.862,
  // },
  // {
  //   place_id: '13',
  //   description: '1 Nguyễn Văn Huyên, Cầu Giấy, Hà Nội, Việt Nam',
  //   main_name_place: 'Vietnam Museum of Ethnology',
  //   latitude: 21.028128,
  //   longitude: 105.796836,
  // },
  // {
  //   place_id: '14',
  //   description: 'Trúc Bạch, Ba Đình, Hà Nội, Việt Nam',
  //   main_name_place: 'Truc Bach Lake',
  //   latitude: 21.052738,
  //   longitude: 105.82328,
  // },
  // {
  //   place_id: '15',
  //   description: '54 Liễu Giai, Ba Đình, Hà Nội, Việt Nam',
  //   main_name_place: 'Lotte Center Hanoi',
  //   latitude: 21.035345,
  //   longitude: 105.817986,
  // },
  // {
  //   place_id: '16',
  //   description: '72 Nguyễn Trãi, Thanh Xuân, Hà Nội, Việt Nam',
  //   main_name_place: 'Royal City',
  //   latitude: 21.016342,
  //   longitude: 105.804431,
  // },
  // {
  //   place_id: '17',
  //   description: 'Hồ Tây, Hà Nội, Việt Nam',
  //   main_name_place: 'Tay Ho',
  //   latitude: 21.050413,
  //   longitude: 105.831456,
  // },
  // {
  //   place_id: '18',
  //   description: '1 Tràng Tiền, Hoàn Kiếm, Hà Nội, Việt Nam',
  //   main_name_place: 'Hanoi Opera House',
  //   latitude: 21.028835,
  //   longitude: 105.858186,
  // },
  // {
  //   place_id: '19',
  //   description: 'Hai Bà Trưng, Hà Nội, Việt Nam',
  //   main_name_place: 'Hai Ba Trung Park',
  //   latitude: 21.021213,
  //   longitude: 105.852135,
  // },
  // {
  //   place_id: '20',
  //   description: 'Đồng Xuân, Hoàn Kiếm, Hà Nội, Việt Nam',
  //   main_name_place: 'Dong Xuan Market',
  //   latitude: 21.034354,
  //   longitude: 105.858168,
  // },
];

export default locationsDataFake;
